apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: hello-world-sensor
  namespace: argo-events
spec:
  dependencies:
    - name: example-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: log-trigger
        k8s:
          group: ""
          version: "v1"
          resource: "Pod"
          operation: "create"
          source:
            resource:
              apiVersion: "v1"
              kind: "Pod"
              metadata:
                generateName: hello-world-
                namespace: argo-events
              spec:
                containers:
                  - name: hello-world
                    image: busybox
                    command: ["/bin/sh", "-c"]
                    args: ["echo Hello, World! && sleep 10"]
