apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
  namespace: argo-events
spec:
  service:
    ports:
      - name: http
        port: 12000
        targetPort: 12000
  webhook:
    example:
      endpoint: /hello-world
      method: POST
      port: "12000" 
